---
keycloak:
  username: admin
  ingress:
    enabled: true
    path: /
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    hosts:
      - keycloak.${local.env}.synthesis-care.com
  persistence:
    deployPostgres: false
    dbVendor: postgres
    existingSecret: "db-keycloak-${local.env}"
    existingSecretKey: "DB_PASSWORD"
    dbName: keycloak
    dbHost: ${dependency.keycloak.outputs.db_instance_address}
    dbPort: 5432
    dbUser: keycloak
