%{ if namespaces != "" }
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: privileged-psp
roleRef:
  kind: ClusterRole
  name: privileged-psp
  apiGroup: rbac.authorization.k8s.io
subjects:
%{ for namespace in split(",", namespaces) ~}
- kind: Group
  name: system:serviceaccounts:${namespace}
  apiGroup: rbac.authorization.k8s.io
%{ endfor ~}
%{ endif }
